[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements_web.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python app.py'