[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = ['pip install -r requirements_web.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'gunicorn app:app --host 0.0.0.0 --port $PORT'