services:
  - type: web
    name: insboo
    env: python
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0